# Generated by Django 4.2.20 on 2025-03-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PickedNumbar',
            new_name='PickedNumber',
        ),
    ]
